Cross-platform basic implementation of CLI commands
explosion/projects pull request #69
Opened 2021-07-14 06:57 UTC by BramVanroy

This PR relates to the issue that I brought up [here](https://github.com/explosion/spaCy/issues/6957). Not all CLI commands are available on all platforms, so the project.yml is not cross-platform.

In this PR I implement cross-platform helper CLI functions for `rm`, `mkdir`, and `mv`. As you may notice, these are relatively basic and not at all as powerful as native commands. But they do work as a stand-in replacement for the original commands.

This PR can serve as a template for the other projects as well, because here I only update the `tagger_parser_ud` project but I do not have the time to update all other projects.

2021-08-11 12:25 UTC, svlandeg commented
Hey Bram,

Thanks for the contribution!

I do agree with you that it would be most ideal if the example projects were working correctly cross-platform. However, the proposed solution here of reimplementing the CI commands seems a little overkill to me - especially if we'd do this for each and every project separately.

Instead, I think it should be more straightforward to just avoid the commands whenever possible (e.g. `spacy train` doesn't require an upfront `mkdir` command for the output), and deal with the rest in custom (pre)processing scripts that just set up the working directory as needed.

2021-08-11 12:34 UTC, svlandeg reviewed
Some suggestions for this specific project

2021-08-11 12:34 UTC, svlandeg commented on pipelines/tagger_parser_ud/project.yml
> +      - "python utils/file.py mv corpus/${vars.treebank}/${vars.test_name}.spacy corpus/${vars.treebank}/test.spacy"
These `mv` statements aren't strictly necessary - we could just keep the original train/dev/test names everywhere in the yml file.

2021-08-11 12:34 UTC, svlandeg commented on pipelines/tagger_parser_ud/project.yml
> +      - "python utils/file.py rm corpus/*"
Here, we could just have a custom Python script that cleans the correct output directories recursively.

2021-08-16 08:40 UTC, svlandeg requested changes
(maintenance note: marking this as "changes requested")

2021-08-16 08:44 UTC, BramVanroy commented
> (maintenance note: marking this as "changes requested")

Hi Sofie. I currently do not have time to work on this. Feel free to either modify this PR or close it. As long as the issue https://github.com/explosion/spaCy/issues/6957 remains open, people are free to contribute. Perhaps you can copy-paste your first reply on this PR about how you think this should be implemented to the issue? Curious people looking for the "help wanted" issue tag might then jump in. :-)

2021-08-16 09:34 UTC, svlandeg commented
Thanks for the note Bram, and thanks for the contribution as well! Please don't feel discouraged to contribute with more PRs in the future ;-)

2021-08-16 09:34 UTC, closed without merging